# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1

workflows:  
  build-image:  
    jobs:
      - build-shopware-arm        
      - build-shopware-amd
      - create-manifest-push:          
          requires:
            - build-shopware-arm
            - build-shopware-amd

        
parameters:
  imageName:
    type: string
    default: ""
  imageTag:
    type: string
    default: ""

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-shopware-arm:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true 
    resource_class: arm.medium

    steps:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y php-cli php-xml unzip
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: php composer-setup.php
      - run: sudo mv composer.phar /usr/local/bin/composer
      
      #Install Dependencies      
      - run: make install

      #ORCA Generate
      - run: make generate phar=1 -B

      #Verify Configuration
      - run: make verify image=<< pipeline.parameters.imageName >> tag=<< pipeline.parameters.imageTag >> -B

      #name: Build Image
      - run: cd ./dist/images/<< pipeline.parameters.imageName >>/<< pipeline.parameters.imageTag >> && DOCKER_BUILDKIT=1 docker build -t dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >> .

      # Run SVRUnit Tests
      - run: make test image=<< pipeline.parameters.imageName >> tag=<< pipeline.parameters.imageTag >> -B

      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Create alias to push as arm64
          command: |
            docker tag dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageName >> dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >>-arm64
      - run:
          name: push amd image
          command: |
            docker push dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageName >>-arm64
  

  build-shopware-amd:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true 
    resource_class: medium

    steps:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y php-cli php-xml unzip
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - run: php composer-setup.php
      - run: sudo mv composer.phar /usr/local/bin/composer

      #Install Dependencies      
      - run: make install

      #ORCA Generate
      - run: make generate phar=1 -B

      #Verify Configuration
      - run: make verify image=<< pipeline.parameters.imageName >> tag=<< pipeline.parameters.imageTag >> -B

      #name: Build Image
      - run: cd ./dist/images/<< pipeline.parameters.imageName >>/<< pipeline.parameters.imageTag >> && DOCKER_BUILDKIT=1 docker build -t dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >> .

      # Run SVRUnit Tests
      - run: make test image=<< pipeline.parameters.imageName >> tag=<< pipeline.parameters.imageTag >> -B
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Create alias to push as amd64
          command: |
            docker tag dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >> dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >>-amd64
      - run:
          name: push amd image
          command: |
            docker push dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >>-amd64
  
  create-manifest-push:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true 
    resource_class: medium
    
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            
      - run: docker manifest create dockerhub.com/dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >> --amend dockerhub.com/dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >>-amd64 --amend dockerhub.com/dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >>-arm64
      
      - run: docker manifest push dockerhub.com/dockware/<< pipeline.parameters.imageName >>:<< pipeline.parameters.imageTag >>



        