name: Custom Image
run-name: Shopware ${{ github.event.inputs.tagName }}

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Image Name'
        required: true
      tagName:
        description: 'Tag Name'
        required: true
      buildArchitecture:
        description: 'Build Architecture'
        required: true
        default: 'multiarch'

jobs:

  build:
    name: Release ${{ github.event.inputs.imageName }}:${{ github.event.inputs.tagName }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Clone Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: make install

      - name: ORCA Generate
        run: make generate -B

      - name: Verify Configuration
        run: make verify image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Build Image
        run: make build image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Run SVRUnit Tests
        run: make test image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B

      - name: Store SVRUnit Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: svrunit_report_${{ github.event.inputs.imageName }}_${{ github.event.inputs.tagName }}
          retention-days: 3
          path: |
            .reports

      - name: Build JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: SVRUnit Tests
          path: .reports/report.xml
          reporter: jest-junit

      - name: Start Image
        run: |
          docker run --rm -p 80:80 --name shop -d dockware/${{ github.event.inputs.imageName }}:${{ github.event.inputs.tagName }}
          sleep 30
          docker logs shop

      - name: Install Cypress
        run: cd tests/cypress && make install -B

      - name: Run Cypress Tests
        run: |
          if [[ $DW_IMAGE == flex ]]; then
             cd tests/cypress && make run-flex url=http://localhost
          fi
          if [[ $DW_IMAGE == essentials ]]; then
             cd tests/cypress && make run-essentials url=http://localhost
          fi
          if [[ $DW_IMAGE == play && $SW_VERSION == latest ]]; then
             cd tests/cypress && make run6 url=http://localhost shopware=6.4.18.0
          fi
          if [[ $DW_IMAGE == dev && $SW_VERSION == latest ]]; then
             cd tests/cypress && make run6 url=http://localhost shopware=6.4.18.0
          fi
          if [[ $SW_VERSION == 6.* ]]; then
             cd tests/cypress && make run6 url=http://localhost shopware=$SW_VERSION
          fi
          if [[ $SW_VERSION == 5.* ]]; then
             cd tests/cypress && make run5 url=http://localhost shopware=$SW_VERSION
          fi
        env:
          DW_IMAGE: ${{ github.event.inputs.imageName }}
          SW_VERSION: ${{ github.event.inputs.tagName }}

      - name: Store Cypress Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress_results_${{ github.event.inputs.imageName }}_${{ github.event.inputs.tagName }}
          retention-days: 1
          path: |
            Tests/Cypress/cypress/videos
            Tests/Cypress/cypress/screenshots     

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Multi-Arch to Docker Hub
        if: ${{ github.event.inputs.buildArchitecture == 'armarch' }}
        run: make build-and-push-multiarch image=${{ github.event.inputs.imageName }} tag=${{ github.event.inputs.tagName }} -B


      - name: Push Amd Arch to Docker Hub
        if: ${{ github.event.inputs.buildArchitecture == 'amdarch' }}
        uses: docker/build-push-action@v3
        with:
          context: ./dist/images/${{ github.event.inputs.imageName }}/${{ github.event.inputs.tagName }}
          push: true
          tags: dockware/${{ github.event.inputs.imageName }}:${{ github.event.inputs.tagName }}